/**
 * Polar (polar.sh) payment integration.
 *
 * Polar is a Merchant of Record like LemonSqueezy. This module mirrors the
 * `lemonSqueezy` helper shape so the checkout route and webhook handler can use
 * either provider.
 *
 * Secrets come from env ONLY — never hardcode the access token or webhook secret:
 *   - POLAR_ACCESS_TOKEN   (server API key, "Select all" scopes)
 *   - POLAR_WEBHOOK_SECRET (generated by Polar when you create the webhook)
 *
 * Product IDs are NOT secret. The live monthly product IDs are the defaults
 * below; override with env if they ever change. Yearly products don't exist yet
 * on Polar — add POLAR_PRODUCT_*_YEARLY when you create them, otherwise a yearly
 * selection falls back to the monthly product.
 */
import crypto from 'crypto'

const POLAR_API = 'https://api.polar.sh/v1'

type PaidPlan = 'starter' | 'growth' | 'business'
type Cycle = 'monthly' | 'yearly'

const PRODUCTS: Record<PaidPlan, { monthly?: string; yearly?: string }> = {
  starter: {
    monthly: process.env.POLAR_PRODUCT_STARTER_MONTHLY || '99db461b-9669-4df7-ae00-aa8c7cca797d',
    yearly: process.env.POLAR_PRODUCT_STARTER_YEARLY,
  },
  growth: {
    monthly: process.env.POLAR_PRODUCT_GROWTH_MONTHLY || 'd65ea916-24c3-4ce4-ae66-a8baa0c7e4ea',
    yearly: process.env.POLAR_PRODUCT_GROWTH_YEARLY,
  },
  business: {
    monthly: process.env.POLAR_PRODUCT_BUSINESS_MONTHLY || '591eb536-2ca8-4190-993a-b9c3d0245b81',
    yearly: process.env.POLAR_PRODUCT_BUSINESS_YEARLY,
  },
}

function token(): string {
  return process.env.POLAR_ACCESS_TOKEN || ''
}

function appUrl(): string {
  return (process.env.NEXT_PUBLIC_APP_URL || 'https://ai-review-writer.vercel.app').replace(/\/$/, '')
}

export interface PolarMeta {
  userId?: string
  plan?: string
  billingCycle?: string
}

export const polar = {
  /** True when the server access token is present. */
  isConfigured(): boolean {
    return !!token()
  },

  /** True when the webhook secret is present (needed to verify callbacks). */
  webhookConfigured(): boolean {
    return !!process.env.POLAR_WEBHOOK_SECRET
  },

  /** Resolve the Polar product ID for a plan + billing cycle. */
  productFor(plan: PaidPlan, cycle: Cycle): string | null {
    const p = PRODUCTS[plan]
    if (!p) return null
    if (cycle === 'yearly' && p.yearly) return p.yearly
    return p.monthly || null
  },

  /**
   * Create a hosted checkout session. Returns { id, url } or null on failure.
   * `userId` is embedded in metadata so the webhook can attribute the purchase.
   */
  async createCheckout(
    plan: PaidPlan,
    cycle: Cycle,
    opts: { userId: string; userEmail?: string; userName?: string }
  ): Promise<{ id: string; url: string } | null> {
    const productId = this.productFor(plan, cycle)
    if (!productId) {
      console.error('[Polar] No product configured for', plan, cycle)
      return null
    }

    try {
      const res = await fetch(`${POLAR_API}/checkouts/`, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token()}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          products: [productId],
          success_url: `${appUrl()}/dashboard?checkout_id={CHECKOUT_ID}&upgraded=1`,
          ...(opts.userEmail ? { customer_email: opts.userEmail } : {}),
          metadata: {
            userId: opts.userId,
            plan,
            billingCycle: cycle,
            ...(opts.userName ? { userName: opts.userName } : {}),
          },
        }),
      })

      if (!res.ok) {
        const detail = await res.text().catch(() => '')
        console.error('[Polar] checkout creation failed:', res.status, detail.slice(0, 500))
        return null
      }

      const data = await res.json()
      if (!data?.url) {
        console.error('[Polar] checkout response missing url')
        return null
      }
      return { id: data.id, url: data.url }
    } catch (e) {
      console.error('[Polar] checkout error:', e)
      return null
    }
  },

  /**
   * Verify a webhook using the Standard Webhooks scheme (Polar's format).
   * Headers: webhook-id, webhook-timestamp, webhook-signature ("v1,<b64> ...").
   * The secret may be base64 (optionally "whsec_"-prefixed) or raw text — we try
   * both to be robust to however the secret was generated.
   */
  verifyWebhook(headers: Headers, payload: string): boolean {
    const secret = process.env.POLAR_WEBHOOK_SECRET || ''
    if (!secret) return false

    const id = headers.get('webhook-id') || ''
    const ts = headers.get('webhook-timestamp') || ''
    const sigHeader = headers.get('webhook-signature') || ''
    if (!id || !ts || !sigHeader) return false

    const signed = `${id}.${ts}.${payload}`
    const cleaned = secret.startsWith('whsec_') ? secret.slice(6) : secret

    const keys: Buffer[] = []
    try {
      const b = Buffer.from(cleaned, 'base64')
      if (b.length > 0) keys.push(b)
    } catch {
      /* not base64 */
    }
    keys.push(Buffer.from(secret, 'utf8'))

    const expected = keys.map((k) =>
      crypto.createHmac('sha256', k).update(signed).digest('base64')
    )
    const provided = sigHeader
      .split(' ')
      .map((s) => (s.includes(',') ? s.slice(s.indexOf(',') + 1) : s))
      .filter(Boolean)

    for (const e of expected) {
      for (const p of provided) {
        if (e.length === p.length && crypto.timingSafeEqual(Buffer.from(e), Buffer.from(p))) {
          return true
        }
      }
    }
    return false
  },

  /** Pull userId/plan/billingCycle from a webhook object's various metadata spots. */
  extractMeta(data: any): PolarMeta {
    const m =
      data?.metadata ||
      data?.subscription?.metadata ||
      data?.checkout?.metadata ||
      data?.order?.metadata ||
      {}
    return {
      userId: m.userId,
      plan: m.plan,
      billingCycle: m.billingCycle,
    }
  },
}
