'use client'

import { motion, AnimatePresence } from 'framer-motion'
import { 
  BarChart3, Sparkles, Download, RefreshCw, MessageSquare, 
  Star, CheckCircle, Bot, Activity, Globe, PieChart, 
  ArrowUpRight, ArrowDownRight, Minus, Lightbulb, 
  Cpu, Clock3, Users, AlertCircle 
} from 'lucide-react'
import { AppRouterInstance } from 'next/dist/shared/lib/app-router-context.shared-runtime'
import { AnalyticsData, AIInsight } from './types'
import { ModernStatCard } from './DashboardStats'
import { 
  ModernLineChart, PlatformDistributionCard, SentimentCard 
} from './DashboardCharts'

interface AnalyticsTabProps {
  data: AnalyticsData | null
  loading: boolean
  stats: AnalyticsData['stats']
  timeRange: number
  setTimeRange: (range: number) => void
  refreshing: boolean
  fetchAnalytics: () => Promise<void>
  showAIInsightsPanel: boolean
  setShowAIInsightsPanel: (show: boolean) => void
  setShowExportModal: (show: boolean) => void
  aiInsights: AIInsight[]
  router: AppRouterInstance
}

export default function AnalyticsTab({
  data,
  loading,
  stats,
  timeRange,
  setTimeRange,
  refreshing,
  fetchAnalytics,
  showAIInsightsPanel,
  setShowAIInsightsPanel,
  setShowExportModal,
  aiInsights,
  router
}: AnalyticsTabProps) {
  return (
    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-6 pt-2 sm:pt-4">
      {/* Header with Controls */}
      <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between gap-4 pb-6 border-b border-white/5">
        <div>
          <h2 className="text-xl sm:text-2xl lg:text-3xl font-bold text-white flex items-center gap-3">
            <div className="rounded-xl bg-purple-500/20 p-2">
              <BarChart3 className="h-6 w-6 text-purple-400" />
            </div>
            Analytics Dashboard
          </h2>
          <p className="text-gray-500 mt-1 sm:ml-12">
            Deep insights into your review performance powered by AI
          </p>
        </div>
        
        <div className="flex flex-wrap items-center gap-3">
          {/* AI Insights Toggle */}
          <button
            onClick={() => setShowAIInsightsPanel(!showAIInsightsPanel)}
            className={`flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-medium transition-all ${
              showAIInsightsPanel 
                ? 'border-purple-500/50 bg-purple-500/10 text-purple-400' 
                : 'border-white/10 bg-white/5 text-gray-400 hover:text-white'
            }`}
          >
            <Sparkles className="h-4 w-4" />
            AI Insights
          </button>
          
          {/* Export Button */}
          <button
            onClick={() => setShowExportModal(true)}
            className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-medium text-gray-400 hover:text-white transition-all"
          >
            <Download className="h-4 w-4" />
            Export
          </button>
          
          {/* Time Range */}
          <div className="flex items-center gap-1 rounded-lg border border-white/10 bg-white/5 p-1">
            {[7, 30, 90].map((days) => (
              <button
                key={days}
                onClick={() => setTimeRange(days)}
                className={`rounded-md px-3 py-1.5 text-sm font-medium transition-all ${
                  timeRange === days ? 'bg-white/10 text-white' : 'text-gray-400 hover:text-white'
                }`}
              >
                {days}D
              </button>
            ))}
          </div>
          
          <button onClick={() => fetchAnalytics()} disabled={refreshing} className="rounded-lg border border-white/10 bg-white/5 p-2 text-gray-400 hover:text-white active:scale-[0.98]">
            <RefreshCw className={`h-5 w-5 ${refreshing ? 'animate-spin' : ''}`} />
          </button>
        </div>
      </div>

      {/* AI Insights Panel */}
      <AnimatePresence>
        {showAIInsightsPanel && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: 'auto' }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <div className="rounded-2xl border border-purple-500/20 bg-purple-500/5 p-4 sm:p-6 mb-6">
              <div className="flex items-center gap-3 mb-6">
                <div className="rounded-xl bg-purple-500/20 p-2">
                  <Sparkles className="h-5 w-5 text-purple-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">AI-Powered Insights</h3>
                  <p className="text-xs text-gray-500">Generated by LongCat AI based on your data</p>
                </div>
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                {aiInsights.map((insight, index) => (
                  <motion.div
                    key={insight.title}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: index * 0.1 }}
                    className="rounded-xl border border-white/10 bg-white/5 p-4"
                  >
                    <div className="flex items-center justify-between mb-3">
                      <div className={`rounded-lg bg-${insight.color}-500/20 p-2`}>
                        <insight.icon className={`h-4 w-4 text-${insight.color}-400`} />
                      </div>
                      <div className={`flex items-center gap-1 text-xs ${
                        insight.trend === 'up' ? 'text-emerald-400' :
                        insight.trend === 'down' ? 'text-rose-400' :
                        'text-gray-400'
                      }`}>
                        {insight.trend === 'up' ? <ArrowUpRight className="h-3 w-3" /> :
                         insight.trend === 'down' ? <ArrowDownRight className="h-3 w-3" /> :
                         <Minus className="h-3 w-3" />}
                        {insight.percentage}%
                      </div>
                    </div>
                    <p className="text-2xl font-bold text-white">{insight.value}</p>
                    <p className="text-sm text-gray-500">{insight.title}</p>
                  </motion.div>
                ))}
              </div>
              
              {/* AI Recommendations */}
              <div className="mt-6 grid grid-cols-1 gap-4">
                <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <CheckCircle className="h-4 w-4 text-emerald-400" />
                    <span className="text-sm font-medium text-emerald-400">What&apos;s Working</span>
                  </div>
                  <ul className="space-y-2 text-sm text-gray-300">
                    <li className="flex items-start gap-2">
                      <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-400" />
                      Your response rate is above industry average
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-400" />
                      AI-generated replies have 85% approval rate
                    </li>
                  </ul>
                </div>
                
                <div className="rounded-xl border border-amber-500/20 bg-amber-500/10 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <Lightbulb className="h-4 w-4 text-amber-400" />
                    <span className="text-sm font-medium text-amber-400">Recommendations</span>
                  </div>
                  <ul className="space-y-2 text-sm text-gray-300">
                    <li className="flex items-start gap-2">
                      <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-amber-400" />
                      Enable auto-reply for 5-star reviews
                    </li>
                    <li className="flex items-start gap-2">
                      <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-amber-400" />
                      Respond to negative reviews within 24 hours
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Stats Grid */}
      {!loading && stats.totalReviews === 0 ? (
        <div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[0.02] to-white/[0.05] p-12 lg:p-20 text-center relative overflow-hidden my-8">
          <div className="absolute top-0 left-1/4 w-[300px] h-[300px] bg-purple-600/20 rounded-full blur-[80px]" />
          <div className="absolute bottom-0 right-1/4 w-[300px] h-[300px] bg-blue-600/20 rounded-full blur-[80px]" />
          
          <div className="relative z-10">
            <div className="w-24 h-24 bg-gradient-to-br from-purple-500/20 to-blue-500/20 border border-white/10 rounded-2xl flex items-center justify-center mx-auto mb-8 shadow-2xl">
              <Bot className="w-12 h-12 text-purple-400" />
            </div>
            <h3 className="text-3xl font-bold text-white mb-4">Your Dashboard is Empty</h3>
            <p className="text-xl text-gray-400 mb-10 max-w-xl mx-auto">Connect your business platforms to start collecting and responding to reviews with AutoReview AI.</p>
            
            <div className="flex flex-col flex-wrap sm:flex-row items-center justify-center gap-4">
              <button onClick={() => router.push('/connect-platforms')}
                className="group relative overflow-hidden rounded-xl bg-purple-600 px-8 py-4 font-semibold text-white transition-all hover:scale-105 hover:shadow-[0_0_30px_rgba(168,85,247,0.4)] active:scale-[0.98]"
              >
                <div className="absolute inset-0 bg-gradient-to-r from-purple-600 to-pink-600 opacity-0 transition-opacity group-hover:opacity-100" />
                <span className="relative flex items-center gap-2">
                  <Globe className="w-5 h-5" /> Connect Platforms
                </span>
              </button>
            </div>
          </div>
        </div>
      ) : (
        <>
          <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
            <ModernStatCard title="Total Reviews" value={stats.totalReviews.toString()} subtitle="All time reviews" icon={MessageSquare} color="blue" delay={0} trend="up" trendValue="12" />
            <ModernStatCard title="Avg Rating" value={stats.avgRating.toString()} subtitle="Out of 5.0 stars" icon={Star} color="amber" delay={0.1} trend="up" trendValue="5" />
            <ModernStatCard title="Response Rate" value={`${stats.responseRate}%`} subtitle={`${stats.repliedReviews} replied`} icon={CheckCircle} color="emerald" delay={0.2} trend="up" trendValue="8" />
            <ModernStatCard title="AI Replies" value={stats.aiGeneratedReplies.toString()} subtitle="Auto-generated" icon={Bot} color="purple" delay={0.3} trend="up" trendValue="15" />
          </div>

          {/* Charts Section */}
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mt-6">
            {/* Activity Chart - Takes 2 columns */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="lg:col-span-2 rounded-2xl border border-white/5 bg-white/[0.02] p-4 sm:p-6"
            >
              <div className="mb-6 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="rounded-lg bg-blue-500/20 p-2">
                    <Activity className="h-5 w-5 text-blue-400" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-white">Review Activity</h3>
                    <p className="text-xs text-gray-500">Reviews over the last {timeRange} days</p>
                  </div>
                </div>
                <div className="flex items-center gap-4 text-sm">
                  <div className="flex items-center gap-2">
                    <span className="h-3 w-3 rounded-full bg-blue-500" />
                    <span className="text-gray-400">Reviews</span>
                  </div>
                </div>
              </div>
              
              {loading ? (
                <div className="h-64 animate-pulse rounded-xl bg-white/5" />
              ) : (
                <ModernLineChart data={(data?.timeSeriesData || []).map(item => ({ date: item.date, value: item.count || 0 }))} color="blue" />
              )}
              
              {/* X-axis labels */}
              <div className="mt-4 flex justify-between text-xs text-gray-500">
                <span>{timeRange} days ago</span>
                <span>Today</span>
              </div>
            </motion.div>

            {/* Platform Distribution */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.5 }}
              className="rounded-2xl border border-white/5 bg-white/[0.02] p-4 sm:p-6"
            >
              <div className="mb-6 flex items-center gap-3">
                <div className="rounded-lg bg-indigo-500/20 p-2">
                  <Globe className="h-5 w-5 text-indigo-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">Platforms</h3>
                  <p className="text-xs text-gray-500">Reviews by source</p>
                </div>
              </div>
              
              {loading ? (
                <div className="h-48 animate-pulse rounded-xl bg-white/5" />
              ) : (
                <PlatformDistributionCard data={data?.platformDistribution || {}} />
              )}
            </motion.div>
          </div>

          {/* Second Row of Charts */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Sentiment Analysis */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.6 }}
              className="rounded-2xl border border-white/5 bg-white/[0.02] p-4 sm:p-6"
            >
              <div className="mb-6 flex items-center gap-3">
                <div className="rounded-lg bg-emerald-500/20 p-2">
                  <PieChart className="h-5 w-5 text-emerald-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">Sentiment Analysis</h3>
                  <p className="text-xs text-gray-500">AI-powered emotion detection</p>
                </div>
              </div>
              
              {loading ? (
                <div className="h-48 animate-pulse rounded-xl bg-white/5" />
              ) : (
                <SentimentCard data={data?.sentimentDistribution || { positive: 0, negative: 0, neutral: 0 }} />
              )}
              
              {/* Sentiment Summary */}
              <div className="mt-6 grid grid-cols-3 gap-4 border-t border-white/5 pt-4">
                {[
                  { label: 'Positive', value: data?.sentimentDistribution?.positive || 0, color: 'text-emerald-400' },
                  { label: 'Neutral', value: data?.sentimentDistribution?.neutral || 0, color: 'text-amber-400' },
                  { label: 'Negative', value: data?.sentimentDistribution?.negative || 0, color: 'text-rose-400' },
                ].map((item) => (
                  <div key={item.label} className="text-center">
                    <p className={`text-2xl font-bold ${item.color}`}>{item.value}</p>
                    <p className="text-xs text-gray-500">{item.label}</p>
                  </div>
                ))}
              </div>
            </motion.div>

            {/* Rating Distribution */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7 }}
              className="rounded-2xl border border-white/5 bg-white/[0.02] p-6"
            >
              <div className="mb-6 flex items-center gap-3">
                <div className="rounded-lg bg-amber-500/20 p-2">
                  <Star className="h-5 w-5 text-amber-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">Rating Distribution</h3>
                  <p className="text-xs text-gray-500">Breakdown by star rating</p>
                </div>
              </div>
              
              {loading ? (
                <div className="h-48 animate-pulse rounded-xl bg-white/5" />
              ) : (
                <div className="space-y-3">
                  {[5, 4, 3, 2, 1].map((stars, index) => {
                    const count = data?.ratingDistribution?.[stars - 1] || 0
                    const total = data?.ratingDistribution?.reduce((a, b) => a + b, 0) || 1
                    const percentage = (count / total) * 100
                    
                    return (
                      <div key={stars} className="flex items-center gap-3">
                        <div className="flex w-12 items-center gap-1">
                          <span className="text-sm font-medium text-white">{stars}</span>
                          <Star className="h-3.5 w-3.5 fill-yellow-500 text-yellow-500" />
                        </div>
                        <div className="flex-1">
                          <div className="h-2.5 overflow-hidden rounded-full bg-white/5">
                            <motion.div
                              initial={{ width: 0 }}
                              animate={{ width: `${percentage}%` }}
                              transition={{ duration: 0.8, delay: index * 0.1 }}
                              className={`h-full rounded-full ${
                                stars >= 4 ? 'bg-emerald-500' :
                                stars === 3 ? 'bg-amber-500' : 'bg-rose-500'
                              }`}
                            />
                          </div>
                        </div>
                        <div className="w-16 text-right">
                          <span className="text-sm text-gray-400">{count}</span>
                          <span className="ml-1 text-xs text-gray-600">({percentage.toFixed(0)}%)</span>
                        </div>
                      </div>
                    )
                  })}
                </div>
              )}
            </motion.div>
          </div>

          {/* AI Performance Section */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.8 }}
            className="rounded-2xl border border-purple-500/20 bg-purple-500/5 p-6"
          >
            <div className="mb-6 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-purple-500/20 p-2">
                  <Cpu className="h-5 w-5 text-purple-400" />
                </div>
                <div>
                  <h3 className="font-semibold text-white">AI Performance Metrics</h3>
                  <p className="text-xs text-gray-500">How AI is helping your business</p>
                </div>
              </div>
              <div className="rounded-full bg-purple-500/20 px-3 py-1 text-xs font-medium text-purple-400">
                Powered by LongCat AI
              </div>
            </div>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <div className="rounded-xl bg-white/5 p-4">
                <p className="text-3xl font-bold text-white">{stats.aiGeneratedReplies}</p>
                <p className="text-sm text-gray-500 mt-1">AI Replies Generated</p>
                <div className="mt-2 flex items-center gap-1 text-xs text-emerald-400">
                  <ArrowUpRight className="h-3 w-3" />
                  <span>+23% this week</span>
                </div>
              </div>
              
              <div className="rounded-xl bg-white/5 p-4">
                <p className="text-3xl font-bold text-white">{stats.editedReplies}</p>
                <p className="text-sm text-gray-500 mt-1">Human Edits</p>
                <div className="mt-2 flex items-center gap-1 text-xs text-amber-400">
                  <Minus className="h-3 w-3" />
                  <span>12% edit rate</span>
                </div>
              </div>
              
              <div className="rounded-xl bg-white/5 p-4">
                <p className="text-3xl font-bold text-emerald-400">
                  {stats.aiGeneratedReplies > 0 
                    ? Math.round((1 - stats.editedReplies / stats.aiGeneratedReplies) * 100) 
                    : 0}%
                </p>
                <p className="text-sm text-gray-500 mt-1">AI Accuracy</p>
                <div className="mt-2 flex items-center gap-1 text-xs text-emerald-400">
                  <ArrowUpRight className="h-3 w-3" />
                  <span>+5% improvement</span>
                </div>
              </div>
              
              <div className="rounded-xl bg-white/5 p-4">
                <p className="text-3xl font-bold text-white">
                  {Math.round((stats.repliedReviews / Math.max(stats.totalReviews, 1)) * 100)}%
                </p>
                <p className="text-sm text-gray-500 mt-1">Response Coverage</p>
                <div className="mt-2 flex items-center gap-1 text-xs text-blue-400">
                  <ArrowUpRight className="h-3 w-3" />
                  <span>On track</span>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Bottom Stats Row */}
          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 sm:gap-4">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.9 }}
              className="rounded-xl border border-white/5 bg-white/[0.02] p-4"
            >
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-blue-500/20 p-2">
                  <Clock3 className="h-5 w-5 text-blue-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-white">2.4h</p>
                  <p className="text-xs text-gray-500">Avg Response Time</p>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.0 }}
              className="rounded-xl border border-white/5 bg-white/[0.02] p-4"
            >
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-cyan-500/20 p-2">
                  <Users className="h-5 w-5 text-cyan-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-white">{stats.totalReviews > 0 ? Math.round(stats.totalReviews / 30) : 0}</p>
                  <p className="text-xs text-gray-500">Reviews per Day</p>
                </div>
              </div>
            </motion.div>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.1 }}
              className="rounded-xl border border-white/5 bg-white/[0.02] p-4"
            >
              <div className="flex items-center gap-3">
                <div className="rounded-lg bg-rose-500/20 p-2">
                  <AlertCircle className="h-5 w-5 text-rose-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-white">{stats.pendingReviews}</p>
                  <p className="text-xs text-gray-500">Awaiting Response</p>
                </div>
              </div>
            </motion.div>
          </div>
        </>
      )}
    </motion.div>
  )
}
